content = open('README.md', 'w')
content.write('# AI-powered Drug Detection NLP Framework with Knowledge Graphs\n\n')
content.write('An AI-powered system that reads handwritten prescriptions using OCR, extracts drug names using BioBERT NLP, and detects dangerous drug interactions using a Knowledge Graph.\n\n')
content.write('## Install\n')
content.write('pip install networkx matplotlib pandas requests tqdm transformers torch torchvision Pillow sentencepiece datasets seqeval\n\n')
content.write('## Run\n')
content.write('python pipeline.py\n\n')
content.write('## Results\n')
content.write('BioBERT fused model: 80% accuracy\n\n')
content.write('## Author\n')
content.write('Sinchana Gowda\n')
content.close()
print('README created!')