content = open('requirements.txt', 'w')
content.write('networkx\n')
content.write('matplotlib\n')
content.write('pandas\n')
content.write('requests\n')
content.write('tqdm\n')
content.write('transformers==4.35.0\n')
content.write('torch\n')
content.write('torchvision\n')
content.write('Pillow\n')
content.write('sentencepiece\n')
content.write('datasets\n')
content.write('seqeval\n')
content.close()
print('requirements.txt created!')